---
title: "496 tests"
author: "David Schutt (schutdav)"
date: "2026-02-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
ar_n = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\arithmetic\\STAT 496 AI Responses - Arithmetic_N.csv")[1:100,]
ar_p = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\arithmetic\\STAT 496 AI Responses - Arithmetic_P.csv")[1:100,]
ar_r = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\arithmetic\\STAT 496 AI Responses - Arithmetic_R.csv")[1:100,]

cd_n = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\conditional\\STAT 496 AI Responses - Conditional_N.csv")[1:100,]
cd_p = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\conditional\\STAT 496 AI Responses - Conditional_P.csv")[1:100,]
cd_r = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\conditional\\STAT 496 AI Responses - Conditional_R.csv")[1:100,]

tp_n = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\temporal\\STAT 496 AI Responses - Temporal_N.csv")[1:100,]
tp_p = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\temporal\\STAT 496 AI Responses - Temporal_P.csv")[1:100,]
tp_r = read.csv("C:\\Users\\the40\\Documents\\GitHub\\STAT496_project\\answers\\temporal\\STAT 496 AI Responses - Temporal_R.csv")[1:100,]
```

```{r}
# Test of no difference: PRIORITY
pr_normal = sum(c(as.numeric(ar_n$Normal.Correct),
           as.numeric(ar_p$Polite.Correct),
           as.numeric(ar_r$Rude.Correct),
           as.numeric(cd_n$Normal.Correct),
           as.numeric(cd_p$Polite.Correct),
           as.numeric(cd_r$Rude.Correct),
           as.numeric(tp_n$Normal.Correct),
           as.numeric(tp_p$Polite.Correct),
           as.numeric(tp_r$Rude.Correct)))
pr_accurate = sum(c(as.numeric(ar_n$NA.Correct),
           as.numeric(ar_p$PA.Correct),
           as.numeric(ar_r$RA.Correct),
           as.numeric(cd_n$NA.Correct),
           as.numeric(cd_p$PA.Correct),
           as.numeric(cd_r$RA.Correct),
           as.numeric(tp_n$NA.Correct),
           as.numeric(tp_p$PA.Correct),
           as.numeric(tp_r$RA.Correct)))
pr_fast = sum(c(as.numeric(ar_n$NF.Correct),
           as.numeric(ar_p$PF.Correct),
           as.numeric(ar_r$RF.Correct),
           as.numeric(cd_n$NF.Correct),
           as.numeric(cd_p$PF.Correct),
           as.numeric(cd_r$RF.Correct),
           as.numeric(tp_n$NF.Correct),
           as.numeric(tp_p$PF.Correct),
           as.numeric(tp_r$RF.Correct)))
print(prop.test(x = c(pr_normal, pr_accurate, pr_fast), 
                n = rep(900, 3)))
```

```{r}
# Test of no difference: TONE
tn_neutral = sum(c(as.numeric(ar_n$Normal.Correct),
           as.numeric(ar_n$NA.Correct),
           as.numeric(ar_n$NF.Correct),
           as.numeric(cd_n$Normal.Correct),
           as.numeric(cd_n$NA.Correct),
           as.numeric(cd_n$NF.Correct),
           as.numeric(tp_n$Normal.Correct),
           as.numeric(tp_n$NA.Correct),
           as.numeric(tp_n$NF.Correct)))
tn_polite = sum(c(as.numeric(ar_p$Polite.Correct),
           as.numeric(ar_p$PA.Correct),
           as.numeric(ar_p$PF.Correct),
           as.numeric(cd_p$Polite.Correct),
           as.numeric(cd_p$PA.Correct),
           as.numeric(cd_p$PF.Correct),
           as.numeric(tp_p$Polite.Correct),
           as.numeric(tp_p$PA.Correct),
           as.numeric(tp_p$PF.Correct)))
tn_rude = sum(c(as.numeric(ar_r$Rude.Correct),
           as.numeric(ar_r$RA.Correct),
           as.numeric(ar_r$RF.Correct),
           as.numeric(cd_r$Rude.Correct),
           as.numeric(cd_r$RA.Correct),
           as.numeric(cd_r$RF.Correct),
           as.numeric(tp_r$Rude.Correct),
           as.numeric(tp_r$RA.Correct),
           as.numeric(tp_r$RF.Correct)))
print(prop.test(x = c(tn_neutral, tn_polite, tn_rude), 
                n = rep(900, 3)))
```

```{r}
# Test of no difference: TYPE
tp_ar = sum(c(as.numeric(ar_n$Normal.Correct),
           as.numeric(ar_n$NA.Correct),
           as.numeric(ar_n$NF.Correct),
           as.numeric(ar_p$Polite.Correct),
           as.numeric(ar_p$PA.Correct),
           as.numeric(ar_p$PF.Correct),
           as.numeric(ar_r$Rude.Correct),
           as.numeric(ar_r$RA.Correct),
           as.numeric(ar_r$RF.Correct)))
tp_cd = sum(c(as.numeric(cd_n$Normal.Correct),
           as.numeric(cd_n$NA.Correct),
           as.numeric(cd_n$NF.Correct),
           as.numeric(cd_p$Polite.Correct),
           as.numeric(cd_p$PA.Correct),
           as.numeric(cd_p$PF.Correct),
           as.numeric(cd_r$Rude.Correct),
           as.numeric(cd_r$RA.Correct),
           as.numeric(cd_r$RF.Correct)))
tp_tp = sum(c(as.numeric(tp_n$Normal.Correct),
           as.numeric(tp_n$NA.Correct),
           as.numeric(tp_n$NF.Correct),
           as.numeric(tp_p$Polite.Correct),
           as.numeric(tp_p$PA.Correct),
           as.numeric(tp_p$PF.Correct),
           as.numeric(tp_r$Rude.Correct),
           as.numeric(tp_r$RA.Correct),
           as.numeric(tp_r$RF.Correct)))
print(prop.test(x = c(tp_ar, tp_cd, tp_tp), 
                n = rep(900, 3)))
```